apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-service-deployment
  labels:
    app: shortener-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortener-service
  template:
    metadata:
      labels:
        app: shortener-service
    spec:
      containers:
        - name: shortener-service
          image: hovo33651/shortener-service:latest
          ports:
            - containerPort: 80

