version: '3.8'

services:
  shortener-service:
    image: hovo33651/shortener-service
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - hazelcast
    networks:
      - shortener-network

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - shortener-network

  hazelcast:
    image: hazelcast/hazelcast:5.2.1
    container_name: hazelcast
    ports:
      - "5701:5701"
#  management-center:
#      image: hazelcast/management-center:5.2.1
#      ports:
#        - "8080:8080"
#      environment:
#        - MC_DEFAULT_CLUSTER=dev
#        - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
#      networks:
#        - shortener-network

networks:
  shortener-network:
    driver: bridge
