spring:
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

hazelcast:
  cache:
    expiration: 300 #minutes
    response-cache: shortener-response-cache
    url-cache: shortened-url-cache

countryidentifier:
  ip-stack-api-key:
  ip-stack-uri:
